### ISSUE TITLE
Problem setting up server in local environment

### ISSUE THREAD

**Issue by Krashcan** [OpenRoberta/robertalab#416]
I am on a windows 10 pc and have followed the instructions mentioned in the readme. It works fine up until the last part `./ora.sh --start-from-git`. Everytime I do this, I get

    $ ./ora.sh --start-from-git
    2017-02-25 18:50:37,693 [main] session-id=[] user-id=[] robot-name=[] INFO de.fhg.iais.roberta.util.Util1 - properties from classpath. Using the resource: openRobertaMailServer.properties
    2017-02-25 18:50:37,693 [main] session-id=[] user-id=[] robot-name=[] INFO de.fhg.iais.roberta.util.Util1 - default properties from classpath. Using the resource: openRoberta.properties
    2017-02-25 18:50:37,693 [main] session-id=[] user-id=[] robot-name=[] INFO d.f.iais.roberta.main.ServerStarter - new property from command line: hibernate.connection.url=jdbc:hsqldb:file:OpenRobertaServer/db/openroberta-db
    2017-02-25 18:50:37,693 [main] session-id=[] user-id=[] robot-name=[] INFO d.f.i.roberta.util.RobertaProperties - As temporary directory C:\Users\KUMARA~1\AppData\Local\Temp\ will be used
    2017-02-25 18:50:37,708 [main] session-id=[] user-id=[] robot-name=[] INFO org.eclipse.jetty.util.log - Logging initialized @558ms
    2017-02-25 18:50:37,739 [main] session-id=[] user-id=[] robot-name=[] INFO d.f.i.r.r.RobotCommunicator - timer thread created
    2017-02-25 18:50:37,739 [main] session-id=[] user-id=[] robot-name=[] INFO de.fhg.iais.roberta.util.Util1 - properties from classpath. Using the resource: Robot.properties
    2017-02-25 18:50:37,777 [main] session-id=[] user-id=[] robot-name=[] INFO de.fhg.iais.roberta.util.Util1 - properties from classpath. Using the resource: EV3.properties
    2017-02-25 18:50:37,793 [main] session-id=[] user-id=[] robot-name=[] INFO de.fhg.iais.roberta.util.Util1 - properties from classpath. Using the resource: Robot.properties
    2017-02-25 18:50:37,793 [main] session-id=[] user-id=[] robot-name=[] INFO de.fhg.iais.roberta.util.Util1 - properties from classpath. Using the resource: Calliope.properties
    2017-02-25 18:50:37,808 [main] session-id=[] user-id=[] robot-name=[] INFO de.fhg.iais.roberta.util.Util1 - properties from classpath. Using the resource: Robot.properties
    2017-02-25 18:50:37,808 [main] session-id=[] user-id=[] robot-name=[] INFO de.fhg.iais.roberta.util.Util1 - properties from classpath. Using the resource: NXT.properties
    2017-02-25 18:50:37,808 [main] session-id=[] user-id=[] robot-name=[] INFO de.fhg.iais.roberta.util.Util1 - properties from classpath. Using the resource: Robot.properties
    2017-02-25 18:50:37,808 [main] session-id=[] user-id=[] robot-name=[] INFO de.fhg.iais.roberta.util.Util1 - properties from classpath. Using the resource: Microbit.properties
    2017-02-25 18:50:37,824 [main] session-id=[] user-id=[] robot-name=[] INFO de.fhg.iais.roberta.util.Util1 - properties from classpath. Using the resource: Robot.properties
    2017-02-25 18:50:37,824 [main] session-id=[] user-id=[] robot-name=[] INFO de.fhg.iais.roberta.util.Util1 - properties from classpath. Using the resource: Ardu.properties
    2017-02-25 18:50:37,824 [main] session-id=[] user-id=[] robot-name=[] INFO de.fhg.iais.roberta.util.Util1 - properties from classpath. Using the resource: Robot.properties
    2017-02-25 18:50:37,824 [main] session-id=[] user-id=[] robot-name=[] INFO de.fhg.iais.roberta.util.Util1 - properties from classpath. Using the resource: NAO.properties
    2017-02-25 18:50:37,840 [main] session-id=[] user-id=[] robot-name=[] INFO d.f.iais.roberta.main.ServerStarter - ROBOT PLUGINS: 6 plugins are found: sim ev3 calliope nxt microbit ardu nao
    2017-02-25 18:50:37,877 [main] session-id=[] user-id=[] robot-name=[] WARN o.e.j.server.handler.ContextHandler - o.e.j.s.ServletContextHandler@49c43f4e{/,null,null} contextPath ends with /*
    2017-02-25 18:50:37,877 [main] session-id=[] user-id=[] robot-name=[] WARN o.e.j.server.handler.ContextHandler - Empty contextPath
    2017-02-25 18:50:37,893 [main] session-id=[] user-id=[] robot-name=[] INFO org.eclipse.jetty.server.Server - jetty-9.2.17.v20160517
    Feb 25, 2017 6:50:38 PM com.sun.jersey.api.core.PackagesResourceConfig init
    INFO: Scanning for root resource and provider classes in the packages:
      de.fhg.iais.roberta.javaServer.restServices.all
      de.fhg.iais.roberta.javaServer.restServices.robot
      de.fhg.iais.roberta.javaServer.provider
    Feb 25, 2017 6:50:38 PM com.sun.jersey.api.core.ScanningResourceConfig logClasses
    INFO: Root resource classes found:
      class de.fhg.iais.roberta.javaServer.restServices.robot.Ev3Update
      class de.fhg.iais.roberta.javaServer.restServices.robot.RobotSensorLogging
      class de.fhg.iais.roberta.javaServer.restServices.all.ClientToolbox
      class de.fhg.iais.roberta.javaServer.restServices.all.Alive
      class de.fhg.iais.roberta.javaServer.restServices.all.ClientPing
      class de.fhg.iais.roberta.javaServer.restServices.all.ClientUser
      class de.fhg.iais.roberta.javaServer.restServices.robot.RobotDownloadProgram
      class de.fhg.iais.roberta.javaServer.restServices.all.ClientAdmin
      class de.fhg.iais.roberta.javaServer.restServices.all.ClientConfiguration
      class de.fhg.iais.roberta.javaServer.restServices.all.ClientProgram
      class de.fhg.iais.roberta.javaServer.restServices.robot.RobotCommand
      class de.fhg.iais.roberta.javaServer.restServices.all.RestExample
    Feb 25, 2017 6:50:38 PM com.sun.jersey.api.core.ScanningResourceConfig logClasses
    INFO: Provider classes found:
      class de.fhg.iais.roberta.javaServer.provider.JAXBMarshallerProvider
      class de.fhg.iais.roberta.javaServer.provider.JAXBContextProvider
      class de.fhg.iais.roberta.javaServer.provider.OraDataProvider
      class de.fhg.iais.roberta.javaServer.provider.JAXBUnmarshallerProvider
    Feb 25, 2017 6:50:38 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
    INFO: Registering de.fhg.iais.roberta.javaServer.restServices.all.ClientAdmin as a root resource class
    Feb 25, 2017 6:50:38 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
    INFO: Registering de.fhg.iais.roberta.javaServer.restServices.all.ClientConfiguration as a root resource class
    Feb 25, 2017 6:50:38 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
    INFO: Registering de.fhg.iais.roberta.javaServer.restServices.all.ClientToolbox as a root resource class
    Feb 25, 2017 6:50:38 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
    INFO: Registering de.fhg.iais.roberta.javaServer.restServices.all.ClientProgram as a root resource class
    Feb 25, 2017 6:50:38 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
    INFO: Registering de.fhg.iais.roberta.javaServer.restServices.all.ClientUser as a root resource class
    Feb 25, 2017 6:50:38 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
    INFO: Registering de.fhg.iais.roberta.javaServer.restServices.robot.RobotDownloadProgram as a root resource class
    Feb 25, 2017 6:50:38 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
    INFO: Registering de.fhg.iais.roberta.javaServer.restServices.robot.RobotCommand as a root resource class
    Feb 25, 2017 6:50:38 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
    INFO: Registering de.fhg.iais.roberta.javaServer.restServices.robot.RobotSensorLogging as a root resource class
    Feb 25, 2017 6:50:38 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
    INFO: Registering de.fhg.iais.roberta.javaServer.restServices.all.RestExample as a root resource class
    Feb 25, 2017 6:50:38 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory register
    INFO: Registering de.fhg.iais.roberta.javaServer.restServices.all.ClientPing as a root resource class
    Feb 25, 2017 6:50:38 PM com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
    INFO: Initiating Jersey application, version 'Jersey: 1.18.2 10/26/2014 03:51 PM'
    Feb 25, 2017 6:50:38 PM com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory getComponentProvider
    INFO: Binding de.fhg.iais.roberta.javaServer.provider.OraDataProvider to GuiceInjectedComponentProvider
    2017-02-25 18:50:38,952 [main] session-id=[] user-id=[] robot-name=[] INFO o.h.annotations.common.Version - HCANN000001: Hibernate Commons Annotations {4.0.2.Final}
    2017-02-25 18:50:38,973 [main] session-id=[] user-id=[] robot-name=[] INFO org.hibernate.Version - HHH000412: Hibernate Core {4.2.7.Final}
    2017-02-25 18:50:38,973 [main] session-id=[] user-id=[] robot-name=[] INFO org.hibernate.cfg.Environment - HHH000206: hibernate.properties not found
    2017-02-25 18:50:38,973 [main] session-id=[] user-id=[] robot-name=[] INFO org.hibernate.cfg.Environment - HHH000021: Bytecode provider name : javassist
    2017-02-25 18:50:38,989 [main] session-id=[] user-id=[] robot-name=[] INFO org.hibernate.cfg.Configuration - HHH000043: Configuring from resource: hibernate-cfg.xml
    2017-02-25 18:50:38,989 [main] session-id=[] user-id=[] robot-name=[] INFO org.hibernate.cfg.Configuration - HHH000040: Configuration resource: hibernate-cfg.xml
    2017-02-25 18:50:39,036 [main] session-id=[] user-id=[] robot-name=[] INFO org.hibernate.cfg.Configuration - HHH000041: Configured SessionFactory: null
    2017-02-25 18:50:39,090 [main] session-id=[] user-id=[] robot-name=[] INFO o.h.s.j.c.i.ConnectionProviderInitiator - HHH000130: Instantiating explicit connection provider: org.hibernate.service.jdbc.connections.internal.C3P0ConnectionProvider
    2017-02-25 18:50:39,090 [main] session-id=[] user-id=[] robot-name=[] INFO o.h.s.j.c.i.C3P0ConnectionProvider - HHH010002: C3P0 using driver: org.hsqldb.jdbcDriver at URL: jdbc:hsqldb:file:OpenRobertaServer/db/openroberta-db
    2017-02-25 18:50:39,090 [main] session-id=[] user-id=[] robot-name=[] INFO o.h.s.j.c.i.C3P0ConnectionProvider - HHH000046: Connection properties: {user=orA, password=****, autocommit=false}
    2017-02-25 18:50:39,090 [main] session-id=[] user-id=[] robot-name=[] INFO o.h.s.j.c.i.C3P0ConnectionProvider - HHH000006: Autocommit mode: false
    Feb 25, 2017 6:50:39 PM com.mchange.v2.log.MLog <clinit>
    INFO: MLog clients using java 1.4+ standard logging.
    Feb 25, 2017 6:50:39 PM com.mchange.v2.c3p0.C3P0Registry banner
    INFO: Initializing c3p0-0.9.2.1 [built 20-March-2013 10:47:27 +0000; debug? true; trace: 10]
    Feb 25, 2017 6:50:39 PM com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource getPoolManager
    INFO: Initializing c3p0 pool... com.mchange.v2.c3p0.PoolBackedDataSource@32173d17 [ connectionPoolDataSource -> com.mchange.v2.c3p0.WrapperConnectionPoolDataSource@f2f35b26 [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, debugUnreturnedConnectionStackTraces -> false, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, identityToken -> 1hgekg19mwkz93l1qnz9bj|5669c5fb, idleConnectionTestPeriod -> 3600, initialPoolSize -> 5, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 7200, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 100, maxStatements -> 100, maxStatementsPerConnection -> 0, minPoolSize -> 5, nestedDataSource -> com.mchange.v2.c3p0.DriverManagerDataSource@bf940e80 [ description -> null, driverClass -> null, factoryClassLocation -> null, identityToken -> 1hgekg19mwkz93l1qnz9bj|736caf7a, jdbcUrl -> jdbc:hsqldb:file:OpenRobertaServer/db/openroberta-db, properties -> {user=******, password=******, autocommit=false} ], preferredTestQuery -> null, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> false, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, usesTraditionalReflectiveProxies -> false; userOverrides: {} ], dataSourceName -> null, factoryClassLocation -> null, identityToken -> 1hgekg19mwkz93l1qnz9bj|42463763, numHelperThreads -> 3 ]
    2017-02-25 18:50:40,138 [main] session-id=[] user-id=[] robot-name=[] INFO org.hibernate.dialect.Dialect - HHH000400: Using dialect: org.hibernate.dialect.HSQLDialect
    2017-02-25 18:50:40,157 [main] session-id=[] user-id=[] robot-name=[] INFO o.h.e.j.internal.LobCreatorBuilder - HHH000424: Disabling contextual LOB creation as createClob() method threw error : java.lang.reflect.InvocationTargetException
    2017-02-25 18:50:40,455 [main] session-id=[] user-id=[] robot-name=[] INFO o.h.e.t.i.TransactionFactoryInitiator - HHH000399: Using default transaction strategy (direct JDBC transactions)
    2017-02-25 18:50:40,455 [main] session-id=[] user-id=[] robot-name=[] INFO o.h.h.i.a.ASTQueryTranslatorFactory - HHH000397: Using ASTQueryTranslatorFactory
    2017-02-25 18:50:41,016 [main] session-id=[] user-id=[] robot-name=[] INFO d.f.i.r.p.util.SessionFactoryWrapper - created
    2017-02-25 18:50:41,945 [main] session-id=[] user-id=[] robot-name=[] INFO o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@ea9e141{/rest,null,AVAILABLE}
    2017-02-25 18:50:41,946 [main] session-id=[] user-id=[] robot-name=[] INFO o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@5c748168{/ws,null,AVAILABLE}
    2017-02-25T18:50:41.993+0530  WARNING  Multiple Servlet injectors detected. This is a warning indicating that you have more than one GuiceFilter running in your web application. If this is deliberate, you may safely ignore this message. If this is NOT deliberate however, your application may not work as expected.
    2017-02-25 18:50:42,439 [main] session-id=[] user-id=[] robot-name=[] INFO org.hibernate.cfg.Configuration - HHH000043: Configuring from resource: hibernate-cfg.xml
    2017-02-25 18:50:42,439 [main] session-id=[] user-id=[] robot-name=[] INFO org.hibernate.cfg.Configuration - HHH000040: Configuration resource: hibernate-cfg.xml
    2017-02-25 18:50:42,447 [main] session-id=[] user-id=[] robot-name=[] INFO org.hibernate.cfg.Configuration - HHH000041: Configured SessionFactory: null
    2017-02-25 18:50:42,448 [main] session-id=[] user-id=[] robot-name=[] INFO o.h.s.j.c.i.ConnectionProviderInitiator - HHH000130: Instantiating explicit connection provider: org.hibernate.service.jdbc.connections.internal.C3P0ConnectionProvider
    2017-02-25 18:50:42,449 [main] session-id=[] user-id=[] robot-name=[] INFO o.h.s.j.c.i.C3P0ConnectionProvider - HHH010002: C3P0 using driver: org.hsqldb.jdbcDriver at URL: jdbc:hsqldb:file:OpenRobertaServer/db/openroberta-db
    2017-02-25 18:50:42,449 [main] session-id=[] user-id=[] robot-name=[] INFO o.h.s.j.c.i.C3P0ConnectionProvider - HHH000046: Connection properties: {user=orA, password=****, autocommit=false}
    2017-02-25 18:50:42,449 [main] session-id=[] user-id=[] robot-name=[] INFO o.h.s.j.c.i.C3P0ConnectionProvider - HHH000006: Autocommit mode: false
    2017-02-25 18:50:42,502 [main] session-id=[] user-id=[] robot-name=[] INFO org.hibernate.dialect.Dialect - HHH000400: Using dialect: org.hibernate.dialect.HSQLDialect
    2017-02-25 18:50:42,502 [main] session-id=[] user-id=[] robot-name=[] INFO o.h.e.j.internal.LobCreatorBuilder - HHH000424: Disabling contextual LOB creation as createClob() method threw error : java.lang.reflect.InvocationTargetException
    2017-02-25 18:50:42,527 [main] session-id=[] user-id=[] robot-name=[] INFO o.h.e.t.i.TransactionFactoryInitiator - HHH000399: Using default transaction strategy (direct JDBC transactions)
    2017-02-25 18:50:42,528 [main] session-id=[] user-id=[] robot-name=[] INFO o.h.h.i.a.ASTQueryTranslatorFactory - HHH000397: Using ASTQueryTranslatorFactory
    2017-02-25 18:50:42,553 [main] session-id=[] user-id=[] robot-name=[] INFO d.f.i.r.p.util.SessionFactoryWrapper - created
    2017-02-25 18:50:42,816 [main] session-id=[] user-id=[] robot-name=[] INFO o.e.j.server.handler.ContextHandler - Started o.e.j.s.ServletContextHandler@49c43f4e{/,null,AVAILABLE}
    2017-02-25 18:50:42,868 [main] session-id=[] user-id=[] robot-name=[] INFO o.e.jetty.server.ServerConnector - Started ServerConnector@563a89b5{HTTP/1.1}{0.0.0.0:1999}
    2017-02-25 18:50:42,869 [main] session-id=[] user-id=[] robot-name=[] INFO org.eclipse.jetty.server.Server - Started @5708ms
    2017-02-25 18:50:42,869 [main] session-id=[] user-id=[] robot-name=[] INFO d.f.iais.roberta.main.ServerStarter - server started at http://0.0.0.0:1999/rest
    2017-02-25 18:50:43,273 [main] session-id=[] user-id=[] robot-name=[] WARN o.h.e.jdbc.spi.SqlExceptionHelper - SQL Error: -5501, SQLState: 42501
    2017-02-25 18:50:43,274 [main] session-id=[] user-id=[] robot-name=[] ERROR o.h.e.jdbc.spi.SqlExceptionHelper - user lacks privilege or object not found: ROBOT
    2017-02-25 18:50:43,287 [main] session-id=[] user-id=[] robot-name=[] ERROR d.f.iais.roberta.main.ServerStarter - Server was started, but could not connect to the database
    org.hibernate.exception.SQLGrammarException: could not prepare statement
            at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:82) ~[hibernate-core-4.2.7.Final.jar:4.2.7.Final]
            at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:49) ~[hibernate-core-4.2.7.Final.jar:4.2.7.Final]
            at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:125) ~[hibernate-core-4.2.7.Final.jar:4.2.7.Final]
            at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:188) ~[hibernate-core-4.2.7.Final.jar:4.2.7.Final]
            at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:159) ~[hibernate-core-4.2.7.Final.jar:4.2.7.Final]
            at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1859) ~[hibernate-core-4.2.7.Final.jar:4.2.7.Final]
            at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1836) ~[hibernate-core-4.2.7.Final.jar:4.2.7.Final]
            at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1816) ~[hibernate-core-4.2.7.Final.jar:4.2.7.Final]
            at org.hibernate.loader.Loader.doQuery(Loader.java:900) ~[hibernate-core-4.2.7.Final.jar:4.2.7.Final]
            at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:342) ~[hibernate-core-4.2.7.Final.jar:4.2.7.Final]
            at org.hibernate.loader.Loader.doList(Loader.java:2526) ~[hibernate-core-4.2.7.Final.jar:4.2.7.Final]
            at org.hibernate.loader.Loader.doList(Loader.java:2512) ~[hibernate-core-4.2.7.Final.jar:4.2.7.Final]
            at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2342) ~[hibernate-core-4.2.7.Final.jar:4.2.7.Final]
            at org.hibernate.loader.Loader.list(Loader.java:2337) ~[hibernate-core-4.2.7.Final.jar:4.2.7.Final]
            at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:495) ~[hibernate-core-4.2.7.Final.jar:4.2.7.Final]
            at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:357) ~[hibernate-core-4.2.7.Final.jar:4.2.7.Final]
            at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:195) ~[hibernate-core-4.2.7.Final.jar:4.2.7.Final]
            at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1275) ~[hibernate-core-4.2.7.Final.jar:4.2.7.Final]
            at org.hibernate.internal.QueryImpl.list(QueryImpl.java:101) ~[hibernate-core-4.2.7.Final.jar:4.2.7.Final]
            at de.fhg.iais.roberta.persistence.dao.RobotDao.loadRobot(RobotDao.java:30) ~[OpenRobertaServer.jar:na]
            at de.fhg.iais.roberta.main.ServerStarter.checkRobotPluginsDB(ServerStarter.java:308) [OpenRobertaServer.jar:na]
            at de.fhg.iais.roberta.main.ServerStarter.main(ServerStarter.java:85) [OpenRobertaServer.jar:na]
    java.sql.SQLSyntaxErrorException: user lacks privilege or object not found: ROBOT
            at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
            at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
            at org.hsqldb.jdbc.JDBCPreparedStatement.<init>(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
            at org.hsqldb.jdbc.JDBCConnection.prepareStatement(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
            at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_101]
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_101]
            at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_101]
            at com.mchange.v2.c3p0.stmt.GooGooStatementCache$1StmtAcquireTask.run(GooGooStatementCache.java:546) ~[c3p0-0.9.2.1.jar:0.9.2.1]
            at com.mchange.v2.async.ThreadPoolAsynchronousRunner$PoolThread.run(ThreadPoolAsynchronousRunner.java:648) ~[mchange-commons-java-0.2.3.4.jar:na]
    Caused by: org.hsqldb.HsqlException: user lacks privilege or object not found: ROBOT
            at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
            at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
            at org.hsqldb.SchemaManager.getTable(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
            at org.hsqldb.ParserDQL.readTableName(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
            at org.hsqldb.ParserDQL.readTableOrSubquery(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
            at org.hsqldb.ParserDQL.XreadTableReference(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
            at org.hsqldb.ParserDQL.XreadFromClause(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
            at org.hsqldb.ParserDQL.XreadTableExpression(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
            at org.hsqldb.ParserDQL.XreadQuerySpecification(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
            at org.hsqldb.ParserDQL.XreadSimpleTable(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
            at org.hsqldb.ParserDQL.XreadQueryPrimary(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
            at org.hsqldb.ParserDQL.XreadQueryTerm(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
            at org.hsqldb.ParserDQL.XreadQueryExpressionBody(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
            at org.hsqldb.ParserDQL.XreadQueryExpression(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
            at org.hsqldb.ParserDQL.compileCursorSpecification(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
            at org.hsqldb.ParserCommand.compilePart(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
            at org.hsqldb.ParserCommand.compileStatement(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
            at org.hsqldb.Session.compileStatement(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
            at org.hsqldb.StatementManager.compile(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
            at org.hsqldb.Session.execute(Unknown Source) ~[hsqldb-2.3.2.jar:2.3.2]
            ... 8 common frames omitted

I can see it says, couldn't connect to database but I have created a folder db in in server folder and ran the `./ora.sh --createemptydb OpenRoberta/db/openroberta-db` command. After this didn't work, I even tried simply copying dbbase under the name db but the output was same. What should I do?

**Comment by cvejoski** [comment]
Where is the location of the *db* folder? By default It should be in the OpenRobertaServer if you do not want to change the path.

**Comment by Krashcan** [comment]
It is in the OpenRobertaServer folder.

**Comment by cvejoski** [comment]
Can you please clone again the repository, copy dbBase folder as db and run mvn clean install.
This should work I have just tried on Win 10.

**Comment by Krashcan** [comment]
It worked after I re-did the whole thing. I must have done some mistake the first time. Also, I noticed, in the readme to create a new empty database, the command give is `./ora.sh --createemptydb OpenRoberta/db/openroberta-db` , Shouldn't it be `./ora.sh --createemptydb OpenRobertaServer/db/openroberta-db` ?

**Comment by cvejoski** [comment]
Yes, that is correct the read me file is not update

**Comment by cvejoski** [comment]
fixed with 35be632
